language: erlang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git libjansson-dev
  - THIS_DIR=$(cd $(dirname $0); pwd)
  - cd $THIS_DIR
  - git clone https://github.com/keplerproject/luarocks.git
  - cd luarocks
  - git checkout tags/v2.3.0
  - PREFIX="$THIS_DIR/.luarocks"
  - ./configure --prefix=$PREFIX --sysconfdir=$PREFIX/luarocks --force-config
  - make build && make install
  - cd ..
  - rm -rf luarocks
  - ./.luarocks/bin/luarocks install luasocket
  - ./.luarocks/bin/luarocks install luasec
  - ./.luarocks/bin/luarocks install multipart-post
  - ./.luarocks/bin/luarocks install dkjson
  - ./.luarocks/bin/luarocks install oauth
  - ./.luarocks/bin/luarocks install redis-lua
  - ./.luarocks/bin/luarocks install lua-cjson
  - ./.luarocks/bin/luarocks install fakeredis
  - ./.luarocks/bin/luarocks install xml
  - ./.luarocks/bin/luarocks install feedparser
  - ./.luarocks/bin/luarocks install serpent
  - ./.luarocks/bin/luarocks install sha1
  - ./.luarocks/bin/luarocks install lpeg
  

script: 
  - luac -p otouto/*.lua
  - luac -p otouto/plugins/*.lua